### ISSUE TITLE
Dockerfile has incorrect JAVA_HOME value

### ISSUE THREAD

**Issue by brunoborges** [Azure-App-Service/java#11]
The Dockerfile has a JAVA_HOME configuration that points to an empty directory.

Therefore the image will fail to be used by any script that attempts to find the JVM under $JAVA_HOME/bin/java

**Comment by brunoborges** [comment]
See this commit: https://github.com/Azure-App-Service/java/commit/a20c2d5eb6af2c15767cf3d141a07c20520e732e

**Comment by jvano** [comment]
Thanks @brunoborges for letting us know, we are currently working on this fix. 

@shrishrirang

**Comment by shrishrirang** [comment]
https://github.com/Azure-App-Service/java/commit/6a34f21e2a47d010885c15afa5cf7c23aadb0473 fixes this.
